name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository with a fetch depth of 2
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 2

      # Use the StackSpotAI-CICD action to run a remote quick command
      - uses: victorsilvazup/stackspot-ai-execute-rqc@main
        id: rqc
        with:
          CLIENT_ID: ${{ secrets.STK_CLIENT_ID }}
          CLIENT_KEY: ${{ secrets.STK_CLIENT_KEY }}
          CLIENT_REALM: ${{ secrets.STK_CLIENT_REALM }}
          QC_SLUG: code-analysis
          FILE_EXTENSION: .md

      # Check the result of the Remote Quick Command
      - name: Check Remote Quick Command answer
        run: |
          for result in ${{ steps.rqc.outputs.rqc_result }}; do 
            echo "Result $result"
          done
