name: 'Execute StackSpot AI Remote Quick Command Action'

description: 'Execute StackSpot AI Remote Quick Command'

inputs:
  CLIENT_ID:
    description: Account client id
    required: true
  CLIENT_KEY:
    description: Account client secret key
    required: true
  CLIENT_REALM:
    description: Account slug
    required: true
  QC_SLUG:
    description: Quick Command slug
    required: true
  FILE_EXTENSION:
    description: File Extension to detect the changes
    required: true

outputs:
  rqc_result:
    description: "Remote Quick Command answer"
    value: ${{ steps.rqc.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.12' 

    - name: Install python libraries 
      run: pip install requests
      shell: bash

    - name: List changed files
      id: list_changed_files
      shell: bash
      env:
        FILE_EXTENSION: ${{ inputs.FILE_EXTENSION }}
      run: |
        if (git diff --name-only --diff-filter=d HEAD~1 HEAD | grep "\${{ env.FILE_EXTENSION }}$"); then
          echo "Listing detected ${FILE_EXTENSION} files."
          git diff --name-only --diff-filter=d HEAD~1 HEAD | grep "\${{ env.FILE_EXTENSION }}$" > changed_files.txt
        else
          echo "No previous commit found. Listing all ${FILE_EXTENSION} files."
          git ls-files | grep "\${{ env.FILE_EXTENSION }}$" > changed_files.txt
        fi
        echo "CHANGED_FILES=$(cat changed_files.txt | tr '\n' ' ')" >> $GITHUB_ENV

    - name: Run StackSpot AI Remote Quick Command
      id: rqc
      run: python3 ${GITHUB_ACTION_PATH}/remote_quick_command.py
      shell: bash
      env:
        CLIENT_ID: ${{ inputs.CLIENT_ID }}
        CLIENT_KEY: ${{ inputs.CLIENT_KEY }}
        CLIENT_REALM: ${{ inputs.CLIENT_REALM }}
        QC_SLUG: ${{ inputs.QC_SLUG }}
        CHANGED_FILES: ${{ env.CHANGED_FILES }}

branding:
    icon: 'terminal'
    color: 'gray-dark'
