name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 2

      - uses: victorsilvazup/stackspot-ai-execute-rqc@main
        id: rqc
        with:
          CLIENT_ID: ${{ secrets.STK_CLIENT_ID }}
          CLIENT_KEY: ${{ secrets.STK_CLIENT_KEY }}
          CLIENT_REALM: ${{ secrets.STK_CLIENT_REALM }}
          QC_SLUG: code-review
          FILE_EXTENSION: .py

# Check the result of the Remote Quick Command
      - name: Check Remote Quick Command answer
        run: |
          echo "Result ${{ steps.rqc.outputs.rqc_result }}"